username=input("Имя пользователя ")
title=input("Заголовок заметки ")
content=input("Описание заметки ")
status=input("Статус заметки ")
created_date=input('Дата создания заметки в формате "день-месяц-год" ')
issue_date=input('Дата истечения заметки в формате "день-месяц-год" ')

print(username)
print(title)
print(content)
print(status)
print(created_date)
print(issue_date)